version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: badlandlords
    environment:
      POSTGRES_DB: badlandlords
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: